handlers = java.util.logging.ConsoleHandler

.level = LEVEL
nproxy.level = FINE

java.util.logging.ConsoleHandler.level = FINE
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

java.util.logging.SimpleFormatter.format = %1$tH:%1$tM %4$-6s : %5$s %n
# java.util.logging.SimpleFormatter.format = %1$tH:%1$tM %4$-6s : %5$s %6$s %n